version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=roberth
      - POSTGRES_PASSWORD=1104017400
      - POSTGRES_DB=PruebaBackend
    ports:
      - "5432:5432"
    volumes:
      - "~/postgres_data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80